issuetracker/config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :performances
  resources :responses
  resources :comments
  resources :users
  resources :tickets
  resources :login
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users do
        resources :tickets, shallow: true
      end
      resources :tickets
      resources :users
    end 
  end
  resources :users do
    resources :tickets
  end

  resources :tickets do 
    resources :comments
  end

  resources :tickets do 
    resources :responses
  end
 

  resource :user, only: [:show] do
    resources :tickets, only: [:show, :index], shallow: true do
      resources :comments, only: [:show, :index]
      resources :responses, only: [:show, :index]
    end
  end
  
  resources :tickets do
    resources :performances 
  end
end

issuetracker/app/models/ticket.rb
class Ticket < ApplicationRecord
    belongs_to :user
    belongs_to :executive, class_name: "User"
    has_many :comments, dependent: :destroy
    has_many :performances, dependent: :destroy
    has_many :responses, dependent: :destroy
    validates :title, presence: true
    validates :description, presence: true
    has_one_attached :documents
    
end

issuetracker/app/controllers/api/v1/tickets_controller.rb
class API::V1::TicketsController < ApiController
  before_action :set_ticket, only: %i[ show edit update destroy ]

  # GET /tickets or /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1 or /tickets/1.json
  def show
    @tickets = Ticket.all
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets or /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    
    if @ticket.save
      render :show, status: :created, location: @ticket 
    else
      render json: @ticket.errors, status: :unprocessable_entity
    end
    
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    
    if @ticket.update(ticket_params)
      render :show, status: :ok, location: @ticket 
    else
      render json: @ticket.errors, status: :unprocessable_entity 
    end
    
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @ticket.destroy

    head :no_content
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.fetch(:ticket, {}).permit(:title, :description, :priority, :state, :user_id, :executive_id, )
    end
end

issuetracker/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show edit update destroy ]

  # GET /tickets or /tickets.json
  def index
    if params[:search_key]
      @tickets = Ticket.where("title LIKE ? OR id LIKE ? OR state LIKE ? OR priority LIKE ?", 
      "%#{params[:search_key]}%", "%#{params[:search_key]}%", "%#{params[:search_key]}%", "%#{params[:search_key]}%")
    else
      @tickets = Ticket.all
    end
  end

  # GET /tickets/1 or /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets or /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully created." }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully updated." }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url, notice: "Ticket was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.fetch(:ticket, {}).permit(:title, :description, :priority, :category, :state, :label, :key_resolution, :tags, :docs, :user_id, :executive_id, :documents, :creation_date, :limit_date)
    end
end

issuetracker/app/helpers/tickets_helper.rb
module TicketsHelper
end

issuetracker/app/views/tickets/_form.html.erb
<%= form_with(model: ticket) do |form| %>
  <% if ticket.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>
      <ul>
        <% ticket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
    <%else%>
    <div class="mb-3">
        <%= form.label :title, class: "form-label" %>
        <%= form.text_field :title, class: "form-control" %>
      </div>
    <div class="mb-3">
        <%= form.label :description_problem, class: "form-label" %>
        <%= form.text_area :description, class: "form-control" %>
      </div>

  <%= form.check_box :doc %>
<%= form.label :doc, "Add doc?" %>
 <div>
  <%= form.submit %>
  </div> 

  <% end %>
  
  
  
<% end %>

issuetracker/app/views/tickets/_ticket.html.erb
<div id="<%= dom_id ticket %>">
</div>

issuetracker/app/views/tickets/edit.html.erb
<br>
<%= form_with(model: @ticket) do |form| %>
  <% if @ticket.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>
      <ul>
        <% @ticket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
    <%else%>
    <div id='columna5'>
    <h3>Documents</h3>
    <% if @ticket.documents.attached? %>
        <%= link_to image_tag(@ticket.documents, class: "card-img-top", width: "800px"), url_for(@ticket) %>
      <%else %>
      <p></p>
      <%end%>
      </div>
      
    <h3><%=@ticket.title%></h3>
        <h5><strong>Ticket id: </strong><%=@ticket.id%></h5>
        <h5><strong>User: </strong><%=@ticket.user.first_name%><%=" "%><%=@ticket.user.last_name%></h5>        
        <ul class="list-unstyled">
        <h5><strong>Description: </strong><%=@ticket.description%></h5>
        <h5><strong>Executive: </strong><%=@ticket.executive.first_name%><%=" "%><%=@ticket.executive.last_name%></h5>
        <h5><strong>Creation Date: </strong><%=@ticket.creation_date%></h5>
        <h5><strong>Limit Date: </strong><%=@ticket.limit_date%></h5>
    <div class="col">
      <h5><strong>Priority </strong></h5>
    <%= form.select :priority,[["Urgent", "Urgent"], ["High", "High"],["Normal", "Half"], ["Low", "Low"]], selected: :priority%>
    </div>
    <div class="col">
       <h5><strong>State </strong></h5>
    <%= form.select :state, [["Open", "open"], ["Close", "close"], ["Reopen", "reopen"]], selected: :state %>
    </div>
    <div class="col">
        <h5><strong>Category </strong></h5>
        <div id="colp"><%= form.text_field :category, class: "form-control" %></div>
      </div>
    <div class="col">
        <h5><strong>Tags </strong></h5>
        <div id="colp"><%= form.text_area :tags, class: "form-control" %></div>
      </div>
       <div class="col">
        <h5><strong>Key Resolution </strong></h5>
        <div id="colp"><%= form.text_area :key_resolution, class: "form-control" %></div>
      </div>
      <div class="col">
        <h5><strong>Documents </strong></h5>
        <%= form.file_field :documents, class: "form-control-file" %>
      </div>  
 <div>
 <p> </p>
  <%= form.submit %>
  </div> 

  <% end %>  
<% end %>

<div>
  <%= link_to "Back to tickets", tickets_path %>
</div>

issuetracker/app/views/tickets/index.html.erb
<p style="color: green"><%= notice %></p>
  <h1>Tickets List</h1>
      <form action="<%= @ticket %>" style='margin-left:800px;'>
      <input type="text" style='border: lightblue 3px outset;'  placeholder="Ticket" name="search_key">
      <button type="submit" class="btn btn-info btn-m" >Search</button>
    </form>
  <div>
<button type="button" class="btn btn-outline-info btn-m " ><%= link_to "Create new Ticket", new_user_ticket_path(@user_id=1,@ticket)%> </button>
<button type="button" class="btn btn-outline-info" ><%= link_to "Back", root_path %> </button>
  </div>

  <table class="table">
  <thead class="bg-info">
      <th>ID</th>
      <th>Email</th>
      <th>User</th>
      <th>Title</th>
      <th>Executive</th>
      <th>State</th>
      <th>Creation Date</th>
      <th>Priority</th>
      <th>View</th>
      <th>Edit</th>
      <th>Delete</th>
      </thead>
  <% @tickets.each do |ticket| %>
    <%= render ticket %>
          <tr>
          <td><%=ticket.id%></td>
          <td><%=ticket.user.email%></td>
          <td><%=ticket.user.first_name%><%=" "%><%=ticket.user.last_name%></td>
          <td><%=ticket.title%></td>
          <td><%=ticket.executive.first_name%><%=" "%><%=ticket.executive.last_name%></td>
          <td><%=ticket.state%></td>
          <td><%=ticket.creation_date%></td>
          <% if ticket.priority=="High" %>
          <td><div style="border-radius 10px; -moz-border-radius 10px; -webkit-border-radius 10px; width: 40px; height: 25px; background:  #78d071; border: solid with 1px;"><strong><%=ticket.priority%></strong></div></td>
          <% else-if ticket.priority=="Half" %>
          <td><div style="border-radius 10px; -moz-border-radius 10px; -webkit-border-radius 10px; width: 35px; height: 25px; background:   rgba(18, 39, 230, 0.596); border: solid with 1px;"><strong><%=ticket.priority%></strong></div></td>
          <% else-if ticket.priority=="Low" %>
          <td><div style="border-radius 10px; -moz-border-radius 10px; -webkit-border-radius 10px; width: 35px; height: 25px; background:  #eef557 ; border: solid with 1px;"><strong><%=ticket.priority%></strong></div></td>
          <% else-if ticket.priority=="Urgent" %>
          <td><div style="border-radius 10px; -moz-border-radius 10px; -webkit-border-radius 10px; width: 60px; height: 25px; background:  rgba(230, 18, 18, 0.541); border: solid with 1px;"><strong><%=ticket.priority%></strong></div></td>
          <%else%>
          <td><strong><%=ticket.priority%></strong></td>
          <%end%>
          <%end%>
          <%end%>
          <%end%>
          <td><button type="button" class="btn btn-sm btn-outline-secondary" ><%= link_to "View", ticket %></button></td>
          <td><button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Edit", edit_ticket_path(ticket) %></button></td>
          <td><%= button_to "Delete", ticket_path(ticket), method: :delete, data: { method_turbo_confirm: "Are you sure?" }, class: ['btn', 'btn-danger']  %></td>

        <tr>
  <% end %>

issuetracker/app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= form_with(model: @ticket) do |form| %>
  <% if @ticket.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>
      <ul>
        <% @ticket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
    <%else%>
    <div class="mb-3">
        <h5><strong> Title</strong></h5>
        <div id="colp"><%= form.text_field :title, class: "form-control" %></div>
      </div>
    <div class="mb-3">
        <h5><strong> Description problem </strong></h5>
       <div id="colp"><%= form.text_area :description, class: "form-control" %></div>
        <%=form.hidden_field :state, value: "open" %>
        <%=form.hidden_field :user_id, value: "1" %>
        <%=form.hidden_field :executive_id, value: "4" %>
        <%=form.hidden_field :creation_date, value: Time.now %> 
        <%=form.hidden_field :priority, value: 'Half' %>
        <%=form.hidden_field :limit_date, value: ((Time.now) + (120 * 120 * 48)) %> 
      <div class="mb-3">
        <h5><strong>Documents </strong></h5>
        <%= form.file_field :documents, class: "form-control-file" %>
      </div>  
      </div>
 <div>
  <%= form.submit %>
  </div> 

  <% end %>  
<% end %>
<div>
  <%= link_to "Back to tickets", tickets_path %>
</div>

issuetracker/app/views/tickets/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="row ml-0">
    <div class="col-6">
        <h2><%=@ticket.title%></h2>
        <h4><%="Ticket ID: "%><%=@ticket.id%></h4>
        <h3><%=@ticket.user.first_name%><%=" "%><%=@ticket.user.last_name%></h3><ul class="list-unstyled">
            <li><strong>Description: </strong><%=@ticket.description%></li>
            <li><strong>Category: </strong><%=@ticket.category%></li>
            <li><strong>Priority: </strong><%=@ticket.priority%></li>
            <li><strong>State: </strong><%=@ticket.state%></li>
            <li><strong>Executive: </strong><%=@ticket.executive.first_name%><%=" "%><%=@ticket.executive.last_name%></li>
            <li><strong>Creation Date: </strong><%=@ticket.creation_date%></li>
            <li><strong>Limit Date: </strong><%=@ticket.limit_date%></li>
            <% if @ticket.state=='close' %>
            <li><strong>Resolution Date: </strong><%=@ticket.resolution_date%></li>
            <%else %>
            <p></p>
            <%end%>
</ul> 
<button type="button" class="btn btn-sm btn-outline-info"><%= link_to "Edit Ticket", edit_user_ticket_path(@ticket.user.id,@ticket) %></button> 
<button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Back to tickets", tickets_path %></button>
<p></p>
<% @ticket.comments.each do |comment| %><%end%>    
<div class="btn-group">
<%if @ticket.state=='open'%>
<button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Comments", new_ticket_comment_path(@ticket,@comment) %></button>
<button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Response", new_ticket_response_path(@ticket,@response)%></button>
<%end%>
<%if @ticket.state=='close'%>
<button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "New performance", new_ticket_performance_path(@ticket,@performance) %></button>    
<%end%>
</div>
<div id="image">
<h3>Documents</h3>
<% if @ticket.documents.attached? %>
    <%= link_to image_tag(@ticket.documents, class: "card-img-top", width: "800px", background: "#55595c", color: "#eceeef"), url_for(@ticket) %>
  <%else %>
  <p></p>
  <%end%>
  </div>
</div>
<div>
    <body>
   <table class="table">
  <thead class="bg-info">
      <th>ID</th>
      <th>Comment</th>
      <th>Executive</th>
      <th>Creation Date</th>
      </thead>
    <tbody>
    <% @ticket.comments.each do |comment| %>
      <tr>
          <td><%=comment.id%></td>
          <td><%=comment.comment%></td>
          <td><%=comment.user.first_name%><%=" "%><%=comment.user.last_name%></td>
          <td><%=comment.comment_date%></td>
        <tr>
    </tbody>
    
    <%end%>
    
    </body>
  </div>
<div>
    <body>
   <table class="table">
  <thead class="bg-info">
      <th>ID</th>
      <th>Response</th>
      <th>Executive</th>
      <th>Creation Date</th>
      </thead>
    <tbody>
    <% @ticket.responses.each do |resp| %>
      <tr>
          <td><%=resp.id%></td>
          <td><%=resp.response%></td>
          <td><%=resp.user.first_name%><%=" "%><%=resp.user.last_name%></td>
          <td><%=resp.response_date%></td>
        <tr>
    </tbody>
    <%end%>
    </body>
  </div>
<%= render @ticket %>

<div>
 </div>
</div>