issuetracker/config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :performances
  resources :responses
  resources :comments
  resources :users
  resources :tickets
  resources :login
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users do
        resources :tickets, shallow: true
      end
      resources :tickets
      resources :users
    end 
  end
  resources :users do
    resources :tickets
  end

  resources :tickets do 
    resources :comments
  end

  resources :tickets do 
    resources :responses
  end
 

  resource :user, only: [:show] do
    resources :tickets, only: [:show, :index], shallow: true do
      resources :comments, only: [:show, :index]
      resources :responses, only: [:show, :index]
    end
  end
  
  resources :tickets do
    resources :performances 
  end
end

issuetracker/app/models/user.rb
class User < ApplicationRecord
    has_many :tickets 
    belongs_to :roll
    has_many :comments
    has_many :performances
    has_many :responses
    validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
    validates :email, presence: true
    validates :email, uniqueness: true
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :phone, presence: true
end

issuetracker/app/controllers/api/v1/users_controller.rb
class API::V1::UsersController < ApiController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @tickets=Ticket.where(executive_id: @user)
  end
  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      render :show, status: :created, location: @user 
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    
    if @user.update(user_params)
      render :show, status: :ok, location: @user 
    else
      render json: @user.errors, status: :unprocessable_entity 
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {}).permit(:email, :first_name, :last_name, :phone, :roll)
    end
end

issuetracker/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    if params[:search_keyU]
      @users = User.where("id LIKE ? OR roll_id LIKE ? OR first_name LIKE ? OR last_name LIKE ?", 
      "%#{params[:search_keyU]}%", "%#{params[:search_keyU]}%", "%#{params[:search_keyU]}%", "%#{params[:search_keyU]}%")
    else
      @users = User.all
    end
  end

  # GET /users/1 or /users/1.json
  def show
    @tickets=Ticket.where(executive_id: @user)
  end
  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {}).permit(:email, :first_name, :last_name, :phone, :roll_id)
    end
end

issuetracker/app/helpers/users_helper.rb
module UsersHelper
end

issuetracker/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
    <%else%>
    <form>
  <div class="form-group">
    <%= form.label :email_adress, class: "form-label" %>
    <%= form.text_field :email, class: "form-control"%>
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  
  <div class="row">
    <div class="col">
    <%= form.label :first_name, class: "form-label" %>
    <%= form.text_field :first_name, class: "form-control"%>
    </div>
    <div class="col">
    <%= form.label :last_name, class: "form-label" %>
    <%= form.text_field :last_name, class: "form-control"%>
    </div>
  </div>
  <div class="form-group">
    <%= form.label :phone, class: "form-label" %>
    <%= form.text_field :phone, class: "form-control"%> 
    <%=form.hidden_field :roll_id, value: "1" %>
  </div>
  <button type="submit" class="btn btn-info">SignUp</button>
</form>
  <% end %>
  
<% end %>

issuetracker/app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
</div>

issuetracker/app/views/users/edit.html.erb
<br>

<%= form_with(model: @user) do |form| %>
  <% if @user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
    <%else%>
    
    <form>
 <h2><%=@user.first_name%><%=" "%><%=@user.last_name%></h2> 
 <h5><%=@user.email%></h5>
          
  <div class="col">
    <h5><strong>Phone </strong></h5>
    <div id="colp"><%= form.text_field :phone, class: "form-control"%></div> 
  </div>
 <div class="col">
    <h5><strong>Roll</strong></h5>
    <%= form.select :roll_id, [["User", "1"], ["Executive", "2"], ["Supervisor", "3"]], selected: :roll_roll %>
</div>
<p></p>
  <div>
  <button type="submit" class="btn btn-info">Update</button>
  </div>
</form>
  <% end %>
  
<% end %>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

issuetracker/app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>
    <body>
    <h1>User List </h1>
    <form action="<%= @ticket %>" style='margin-left:800px;'>
      <input type="text" style='border: lightblue 3px outset;'  placeholder="User" name="search_keyU">
      <button type="submit" class="btn btn-info btn-m" >Search</button>
    </form>
    <div>
<button type="button" class="btn btn-outline-info" ><%= link_to "Back", root_path %> 
</div>
    <table class="table">
  <thead class="bg-info">
      <th>ID</th>
      <th>Name</th>
      <th>Last Name</th>
      <th>Roll</th>
      <th>View</th>
      <th>Edit</th>
      </thead>
    <tbody>
    <% @users.each do |user| %>
    <%= render user %>
        <tr>
          <td><%=user.id%></td>
          <td><%=user.first_name%></td>
          <td><%=user.last_name%></td>
          <td><%=user.roll.roll%></td>
          
              <td><button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "View", user %></button></td>
              <td><button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Edit", edit_user_path(user) %></button></td>
  
        <tr>
    </tbody>
</p>
  <% end %>

issuetracker/app/views/users/new.html.erb
<h1>New user</h1>
<br>
<%= form_with(model: @user) do |form| %>
  <% if @user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
    <%else%>
    
    <form>
    <div class="form-group" id="i">
    <h5><strong>Email adress </strong></h5>
    <div id="colp"><%= form.text_field :email, class: "form-control"%></div>
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  
  <div class="row" id="i">
    <div class="col">
    <h5><strong>First name </strong></h5>
    <div id="colp"><%= form.text_field :first_name, class: "form-control"%></div>
    </div>
    <div class="col" id="i">
    <h5><strong>Last name </strong></h5>
    <div id="colp"><%= form.text_field :last_name, class: "form-control"%></div>
    </div>
  </div>
  <div class="form-group" id="i">
  <h5><strong> Phone </strong></h5>
    <div id="colp"><%= form.text_field :phone, class: "form-control"%></div>
    <%=form.hidden_field :roll_id, value: "1" %>
  </div>
    <%= form.submit %>
</form>
  <% end %>
  
<% end %>

<div>
  <%= link_to "Back to users", users_path %>
</div>

issuetracker/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<%= render @user %>
<div class="row ml-0">
    <div class="col-6">
        <h3><%=@user.first_name%><%=" "%><%=@user.last_name%></h3>
        <h5><%="ID "%><%=@user.id%></h5>
        <ul class="list-unstyled">
            <li><strong>First name: </strong><%=@user.first_name%></li>
            <li><strong>Last name: </strong><%=@user.last_name%></li>
            <li><strong>Email: </strong><%=@user.email%></li>
            <li><strong>Roll: </strong><%=@user.roll.roll%></li>
      </ul>
       <div>
  <button type="button" class="btn btn-outline-info" ><%= link_to "Back", users_path %>
</div>
<p></p>
</div>
</div>
<% if @user.roll.roll=="Executive" %>
<h1>List of assigned tickets</h1>
    <body>
    <table class="table">
  <thead class="bg-info">
      <th>ID</th>
      <th>User</th>
      <th>Title</th>
      <th>State</th>
      <th>Creation Date</th>
      <th>View</th>
      <th>Edit</th>
      </thead>
    <tbody>
    <% @tickets.where(executive_id:@user).sort{|a,b| b.creation_date <=> a.creation_date}.each do |ticket| %>
      <tr>
          <td><%=ticket.id%></td>
          <td><%=ticket.user.first_name%><%=" "%><%=ticket.user.last_name%></td>
          <td><%=ticket.title%></td>
          <td><%=ticket.state%></td>
          <td><%=ticket.creation_date%></td>
          <td><button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "View", ticket %></button></td>
          <td><button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Edit", edit_ticket_path(ticket) %></button></td>
        <tr>
    </tbody>
    <%end%> 
     <%else%>
    <h1>Tickets List</h1>
    <body>
    <table class="table">
  <thead class="bg-info">
      <th>ID</th>
      <th>Title</th>
      <th>State</th>
      <th>Creation Date</th>
      <th>View</th>
      </thead>
    <tbody>
    <% @user.tickets.sort{|a,b| b.creation_date <=> a.creation_date}.each do |ticket| %>
      <tr>
          <td><%=ticket.id%></td>
          <td><%=ticket.title%></td>
          <td><%=ticket.state%></td>
          <td><%=ticket.creation_date%></td>
          <td><button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "View", ticket %></button></td>
        <tr>
    </tbody>
    <%end%>
    
  
<p style="color: green"><%= notice %></p>
  <%end%>