issuetracker/config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :performances
  resources :responses
  resources :comments
  resources :users
  resources :tickets
  resources :login
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users do
        resources :tickets, shallow: true
      end
      resources :tickets
      resources :users
    end 
  end
  resources :users do
    resources :tickets
  end

  resources :tickets do 
    resources :comments
  end

  resources :tickets do 
    resources :responses
  end
 

  resource :user, only: [:show] do
    resources :tickets, only: [:show, :index], shallow: true do
      resources :comments, only: [:show, :index]
      resources :responses, only: [:show, :index]
    end
  end
  
  resources :tickets do
    resources :performances 
  end
end

issuetracker/app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :ticket
    belongs_to :user
    validates :comment, presence: true
end

issuetracker/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @ticket = Ticket.find(params[:ticket_id])
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)
    

    respond_to do |format|
      if @comment.save
        format.html { redirect_to ticket_url(@comment.ticket_id), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.fetch(:comment, {}).permit(:user_id, :comment, :comment_date, :ticket_id)
    end
end

issuetracker/app/helpers/comments_helper.rb
module CommentsHelper
end

issuetracker/app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
</div>

issuetracker/app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

issuetracker/app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

issuetracker/app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>New Comment</h1>
    <h5>ID </h5><%=@ticket.comment.id%>
    <h5>Ticket Title </h5><%=@comment_ticket%>
    <h5>Executive </h5><%=@comment_user%><%=" "%><%=@comment_user%>
    <h5>Date </h5><%=@comment_comment_date%>
    
</div>

issuetracker/app/views/comments/new.html.erb
<h2>New comment</h2>
<%= form_with(model: @comment) do |form| %>
  <% if @comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
        <% @comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
    <%else%>
    <form>
<h4><strong><%="Ticket Title:"%></strong><%=" "%><%=@ticket.title%></h4> 
 <h5><strong><%="Ticket ID:"%></strong><%=" "%><%=@ticket.id%></h5>
  <%=form.hidden_field :user_id, value: @ticket.executive.id%>
  <%=form.hidden_field :ticket_id, value: @ticket.id%>
  <%=form.hidden_field :comment_date, value: Time.now%>

  <div class="form-group">
  <h5><strong> Comment </strong></h5>
  <%=@ticket_id%>
  <div id="colp"><%= form.text_area :comment, class: "form-control"%></div>
  </div>
  <div>
    <%= form.submit %>
  </div>
  </form>
  <% end %>
<% end %>
<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

issuetracker/app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>