issuetracker/config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :performances
  resources :responses
  resources :comments
  resources :users
  resources :tickets
  resources :login
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users do
        resources :tickets, shallow: true
      end
      resources :tickets
      resources :users
    end 
  end
  resources :users do
    resources :tickets
  end

  resources :tickets do 
    resources :comments
  end

  resources :tickets do 
    resources :responses
  end
 

  resource :user, only: [:show] do
    resources :tickets, only: [:show, :index], shallow: true do
      resources :comments, only: [:show, :index]
      resources :responses, only: [:show, :index]
    end
  end
  
  resources :tickets do
    resources :performances 
  end
end

issuetracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
<link rel="stylesheet" href=
"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
        /* Set the border color */
.custom-toggler.navbar-toggler {
            border-color: lightgreen;
        }
        /* Setting the stroke to green using rgb values (0, 128, 0) */
          
        .custom-toggler .navbar-toggler-icon {
            background-image: url(
"data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(0, 128, 0, 0.8)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 8h24M4 16h24M4 24h24'/%3E%3C/svg%3E");
        }
    </style>
</head>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-success fixed-top bg-dark">
        <div class="container-fluid">
          <%= link_to "TechnicDesk", root_path, class: "navbar-brand", style:"margin-left:.5em, bold" %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <%= link_to "User Profile", user_path(1), class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Tickets", tickets_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Performance", performances_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Reports", reports_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "User List", users_path, class: "nav-link" %>
              </li>
               

            </ul>
          </div>
      <%= link_to "SignUp", new_user_path, class: "nav-link"%>
      <%= link_to "LogIn", new_user_path, class: "nav-link", style:"margin-right:.5em" %>

      </div>
    </nav>
  </header>
  <!-- The .container-fluid class provides a full width container, spanning the entire width of the viewport -->
  <main class="container-fluid" style="margin-top: 4em">
    <div class="row">
      
      <div class="col-sm-10" id="main_content">
        <% if notice.present? %>
          <div class="row ml-0 mt-3" role="alert">
            <div id="notice" class="alert alert-success">
              <%= notice %>
            </div>
          </div>
        <% end %>
        <% if alert.present? %>
          <div class="row ml-0 mt-3" role="alert">
            <div id="alert" class="alert alert-danger">
              <%= alert %>
            </div>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </main>
</body>
</html>